spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true

  data:
    rest:
      base-path: /api

  kafka:
    bootstrap-servers:
      - localhost:9092

    template:
      default-topic: tacocloud.orders.topic

    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

taco:
  orders:
    page-size: 20

  discount:
    codes:
      abcdef: 10

logging:
  level:
    tacos: DEBUG

---

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:3306/taco-cloud
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    rest:
      base-path: /api

logging:
  level:
    tacos: WARN
